---
title: "RNoobz Class 2"
output:
  html_document:
    df_print: paged
---

```{r}

rnoobz2 <- read.csv("RNoobz2.csv")

```

#######################
##Practice Question 1##
#######################

```{r}

rnoobz <- seq(1,100,5)
sum(rnoobz)

```

#######################
##Practice Question 2##
#######################

```{r}

rnoobz2 <- read.csv("RNoobz2.csv")
plot(rnoobz2$Age, rnoobz2$P_Sum, type="p", main="My First RNoobz Graph", xlab="Age", ylab="P Sum")


```

#######################
##Practice Question 3##
#######################


```{r}

name <- c("Donald","Melania","Eric", "Ivanka","Donald Jr.","Tiffany","Barron")
name

age <- c(72, 48, 34, 36, 40, 24, 12)
age

covfefe <- c(88.92, 21.78, 63.97,57.00, 1, 99.99, 74.25)
covfefe

trump <- cbind(c(name, age, covfefe))
trump2 <- matrix(trump, nrow=7, ncol=3)
colnames(trump2) <- c("Name", "Age", "Covfefe")
trump2 <-as.data.frame(trump2)
trump2

```

#######################
##Example 1##
#######################

```{r}

str(rnoobz2)

```

#######################
##Example 2##
#######################

```{r}

summary(rnoobz2)

```

#######################
##Example 3##
#######################

```{r}

head(rnoobz2)
head(rnoobz2, n=3)

```

#######################
##Example 4##
#######################

```{r}

tail(rnoobz2)
tail(rnoobz2, n=3)

```

#######################
##Example 5##
#######################

```{r}

library(graphics)

plot(rnoobz2)
plot(rnoobz2$Gender)
plot(rnoobz2$DATE)
plot(rnoobz2$P_Sum)
plot(rnoobz2$CHR)
plot(rnoobz2$T2.)

```

#######################
## Practice Question 4##
#######################


```{r}

library(dplyr)
hist(rnoobz2$Age, breaks=seq(10,60,5), col = "purple", border="blue",  main = "Age of Sample", xlab="Age", ylab="Frequency")

```

#######################
## Example 6##
#######################

```{r}

summarise(rnoobz2, count = n(), mean_age = mean(Age), mean_PSUM = mean(P_Sum))

```

#######################
## Practice Question 5##
#######################

```{r}

summarise(rnoobz2, count = n(), mean_age = mean(Age), stdev_age = sd(Age), min_age = min(Age), max_age = max(Age), mean_P = mean(P_Sum), stdev_P = sd(P_Sum), min_P = min(P_Sum), max_P = max(P_Sum))

```

#######################
## Example 7##
#######################

```{r}

group_by(.data = rnoobz2, CHR) %>% summarise(count = n(), mean_age = mean(Age), stdev_age = sd(Age), min_age = min(Age), max_age = max(Age), mean_P = mean(P_Sum), stdev_P = sd(P_Sum), min_P = min(P_Sum), max_P = max(P_Sum))

```

#######################
## Practice Question 6##
#######################

```{r}

group_by(rnoobz2, Gender) %>% summarise(count = n(), mean_age = mean(Age), mean_P_Sum = mean(P_Sum))

```

#######################
## Example 8##
#######################

```{r}

subset <- select(rnoobz2, ID, CHR, P_Sum)
subset <- select(rnoobz2, STUDY_ID = ID, CHR_STATUS = CHR, PSUM = P_Sum)

```

#######################
## Example 9##
#######################

```{r}

CHR <- filter(rnoobz2, CHR == 1)

```

#######################
## Practice Question 7##
#######################

```{r}

young <- filter(rnoobz2, Age <= 18)
young

young_mean <- summarise(young, mean_age = mean(Age), sd_age = sd(Age))
young_mean

```

#######################
## Practice Question 7##
#######################

```{r}

#Step 1#
group_by(rnoobz2, Age) %>% summarise(count= n())

#Step 2#
group_by(rnoobz2, Age) %>% summarise(count= n(), psum = mean(P_Sum))
plot(data=rnoobz2, rnoobz2$Age, rnoobz2$P_Sum, type="p")

#Step 3#
selected <- filter(rnoobz2, Age >= 12 & Age <= 18 &  CHR == 1)
selected

#Step 3#
mean(selected$P_Sum)
summarise(selected, mean = mean(P_Sum))

#Step 4#
hist(selected$Age, col = "#99d6ff",breaks= seq(12,18,1), border="#002e4d",  main = "Positive Symptom Sum", xlab="Positive Symptom Sum", ylab="Frequency")

```


